### PR TITLE
Updated copyright string

### PR DESCRIPTION
**Pull request by m4rc1e**
Hey @etunni,

I'm currently releasing fonts on behalf of Google Fonts.

I've performed a few regressions tests and only found a minor problem with the OFL and copyright strings. 

Cheers,
Marc

### CODE REVIEW

**Comment by alexeiva** [comment]
thank you @m4rc1e

**Comment by StefanPeev** [comment]
@m4rc1e Please, comment the idea for the [support for modern form of Bulgarian Cyrillic by .loclBGR](https://github.com/etunni/Gabriela/issues/2)

**Comment by m4rc1e** [comment]
@StefanPeev @etunni  Thanks, I see your source is .ufo in #2 . This project is using .glyphs. If you have glyphs, please transfer the glyphs there then make a pull request.

Cheers,
Marc

**Comment by StefanPeev** [comment]
@m4rc1e I'm afraid I don't work with Glyphs editor. Any other possibilities?

**Comment by m4rc1e** [comment]
@davelab6 @alexeiva What do you guys think about this?

Is Bulgarian not included in our standard Cyrillic encodings?

**Comment by m4rc1e** [comment]
I'm transferring the convo to your issue to keep things cleaner.

**Comment by etunni** [comment]
Hi guys, I haven't problem if the added glyphs make that the font extends and improve the range of use.

**Comment by m4rc1e** [comment]
Hey @etunni,

I'm going to submit today what we currently have for Google Fonts. We'll add this in a later release, if the quality is up to scratch and we find the time to work it in.

**Comment by m4rc1e** [comment]
ping @etunni can we merge this?

**Comment by etunni** [comment]
Of course! @m4rc1e

**Comment by davelab6** [comment]
Stefan what editor are you using?

**Comment by StefanPeev** [comment]
FontForge, sometimes FontLab 5.2 and TruFont.

**Pull request merged**
